### ISSUE TITLE
开发服务报错

### ISSUE THREAD

**Issue by jiadesen** [Meqn/vite-plugins#1]
<img width="731" alt="image" src="https://user-images.githubusercontent.com/22772994/195399241-327ce2ed-3f60-43c4-853c-8e31ab56c02b.png">
<img width="715" alt="image" src="https://user-images.githubusercontent.com/22772994/195399395-ce3bdb85-8aa3-47b6-adbb-de095e933874.png">

**Comment by Marinerer** [comment]
@jiadesen 
是的，目前开发环境存在这个问题（暂不影响使用）。
下一版本将会修复。

**Comment by Marinerer** [comment]
@jiadesen 
问题已修复，升级下模块
