### ISSUE TITLE
please update to follow vite5

### ISSUE THREAD

**Issue by silentmissile** [Meqn/vite-plugins#5]
when I update my vite to version 5, and run

> npm run dev

there is hint

> plugin 'vite-plugin-page-html' uses deprecated 'enforce' option. Use 'order' option instead.
> plugin 'vite-plugin-page-html' uses deprecated 'transform' option. Use 'handler' option instead.

could you please update your plugin to follow the new version of vite?

**Comment by naknakLEE** [comment]
same issue

**Comment by Marinerer** [comment]
Sorry, I haven't been following the repo lately.

I will take the time to update it.

**Comment by Marinerer** [comment]
Please upgrade `vite-plugin-page-html@3.x`
